remove hardcoded baudrate in examples
reaper7/SDM_Energy_Meter pull request #54
Opened 2021-03-15 20:16 UTC by bluemanos

I spend a few hours to get the examples working and finally I noticed that even if I setup the baud rate value in `SDM_Config_User.h` file then it is hardcoded in examples.

Lets avoid the mistake in the future in other users :)

2021-03-15 20:57 UTC, reaper7 commented
default SDM_UART_BAUD is defined here: https://github.com/reaper7/SDM_Energy_Meter/blob/master/SDM.h#L21
so...
all your changes are ok except uncommenting SDM_UART_BAUD in SDM_Config_User.h

2021-03-23 22:12 UTC, reaper7 requested changes
leave SDM_UART_BAUD commented out because default value for this definition is specified in this place: https://github.com/reaper7/SDM_Energy_Meter/blob/master/SDM.h#L21

2021-03-24 06:56 UTC, bluemanos commented
@reaper7 done and commit squashed :) sorry for so long response.

2021-03-24 07:03 UTC, reaper7 approved these changes

2021-03-24 07:03 UTC, merged

2021-03-24 07:03 UTC, reaper7 commented
ok, tnx :)